#! /bin/sh

function dual_monitor() {
    bspc monitor $2 -n 1 -d IV V VI VII IIX IX X
    bspc monitor $1 -n 0 -d I II III

    bspc monitor 1 -d 4 5 6 7 8 9 10
    bspc monitor 0 -d 1 2 3

    bspc monitor $2 -s $1
}

export PATH=$HOME/.scripts/:$PATH

# Monitor setup
bspc monitor any --reset-desktops

if [[ $(xrandr -q | grep -w DP-0) =~ \ connected ]]; then
    $HOME/.screenlayout/HOME.sh
    dual_monitor "DP-0" "eDP-1-1"

elif [[ $(xrandr -q | grep -w HDMI-0) =~ \ connected ]]; then
    $HOME/.screenlayout/WORK.sh
    dual_monitor "HDMI-0" "eDP-1-1"

else
    $HOME/.screenlayout/SINGLE.sh

    # Use the first monitor name we see (depends on the use of video driver)
    bspc monitor "$(xrandr -q | grep \ connected | head -n 1 | awk '{print $1;}')" -n 1 -d I II III IV V VI VII IIX IX X

    bspc monitor 1 -d 1 2 3 4 5 6 7 8 9 10
fi

# BSPWM Specific

pgrep -x sxhkd > /dev/null || sxhkd &

bspc config border_width         0
bspc config window_gap          15

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config paddingless_monocle  true

# One-shots

bspc rule -a firefox desktop=2 --one-shot
# bspc rule -a kitty desktop=1 --one-shot

# Consistent

bspc rule -a notion-app desktop=1
bspc rule -a Spotify desktop=4
bspc rule -a Whatsapp-for-linux desktop=5
bspc rule -a discord desktop=6
bspc rule -a Steam desktop=8
bspc rule -a Code desktop=3
bspc rule -a Slack desktop=6
bspc rule -a jetbrains-idea desktop=3
bspc rule -a Postman desktop=7
bspc rule -a Todoist desktop=1

bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled
bspc rule -a origin.exe state=floating

# Background applications

exec $HOME/.config/polybar/launch_hidden.sh --forest 3 &
exec /usr/lib/geoclue-2.0/demos/agent &
exec $(pkill redshift; redshift) &
exec feh --bg-scale ~/Pictures/wallpaper.jpg &
exec $(pkill dunst; dunst -config $HOME/.config/dunst/dunstrc) &
exec picom --corner-radius 10 &

# Startup applications

exec startups &
emacs --daemon
$HOME/.scripts/hellowikipedia.sh
