#!/bin/bash

# if [[ $(ls -al /tmp/ | grep .launched) ]]; then
# 	exit 0
# fi

# touch /tmp/.launched
function startnotrunning() {
	ps aux | grep $1 | head -n -1 | grep $1 || $1 & 
}

startnotrunning firefox
startnotrunning whatsapp-for-linux

