#!/bin/bash

function startnotrunning() {
	ps aux | grep $1 | head -n -2 | grep $1 || "$@" & 
}

startnotrunning kitty 
startnotrunning firefox
startnotrunning whatsapp-for-linux
startnotrunning todoist
startnotrunning discord
startnotrunning webwhatsapp
